# Generated by Django 4.2.8 on 2024-05-02 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveSmallIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.checkout')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
