# Generated by Django 4.2.8 on 2024-05-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0006_alter_movie_options'),
        ('checkout', '0002_checkout_checkoutitem_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutItemCustom',
            fields=[
                ('checkoutitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.checkoutitem')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            bases=('checkout.checkoutitem',),
        ),
    ]
