# Generated by Django 4.2.8 on 2024-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_checkoutitem_delete_order'),
        ('movies', '0006_alter_movie_options'),
        ('checkout_custom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutItemCustom',
            new_name='CustomCheckoutItem',
        ),
    ]
