# Generated by Django 4.2.8 on 2024-04-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
