# Generated by Django 4.2.8 on 2024-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_genre_name_alter_movie_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
