# Generated by Django 4.2.8 on 2024-05-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_daily_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title', 'release_year']},
        ),
    ]
